/**
 *  SoftChalk LessonBuilder
 *  ================ DO NOT EDIT ================
 */

q_item=5;
group_item=2;
tableToggle_array=new Array();
f_done=new Array();
feed=new Array();
q_done=new Array();
scoreQ=new Array();
qOrder=new Array();
qOrder[0]=3;
qOrder[1]=4;
qOrder[2]=5;
num_pages=9;
//groupOrder2=3,4,5
//groupName2=ModuleIIIQuiz
//groupOneAtATime2=false
//groupRandom2=false
//groupPoolSize2=3
//groupRetry2=false
//groupShow2=false
//groupScoreSummary2=false
//groupBorder2=true
scorm_completed_status=true;

//q_num=3;
inline_feedback3=true;
q_done[3]=false;
q_value3=1;
scoreQ[3]="yes";
mc_items3=2;
//ra_items3=1;
q_type3=2;
theQuestion3="YouTube's automatic captioning feature produces captions that are 100% accurate.";
showCorrect3="yes";
showHint3="no";
showFeedbackIndividual3="yes";
case_sensitive3="false";
partial_credit3=false;
feedbackRight3="Right! Good job!";
feedbackWrong3="Sorry, incorrect answer. Automatic captioning is usually, at least somewhat, inaccurate and will require additional editing.";
feedbackPartial3="Partially correct.";
hint3="";
feedbackIndividual3=new Array(8);
feedbackIndividual3[0]="";
feedbackIndividual3[1]="";
feedbackIndividual3[2]="";
feedbackIndividual3[3]="";
feedbackIndividual3[4]="";
feedbackIndividual3[5]="";
feedbackIndividual3[6]="";
feedbackIndividual3[7]="";
right_answers3=new Array(1);
right_answers3[0]="false";
answer_choices3=new Array(2);
answer_choices3[0]="True";
answer_choices3[1]="False";
tableToggle_array[3]=true;
f_done[3]=false;
feed[3]=false;
//colorChoice3="_custom";
//tableClass3="expand";
//openerImage3="none.gif";
//allowRetry3=true;
//groupID3=2;

//q_num=4;
inline_feedback4=true;
q_done[4]=false;
q_value4=1;
scoreQ[4]="yes";
mc_items4=3;
//ra_items4=3;
q_type4=6;
theQuestion4="Put the items in the correct order.";
showCorrect4="no";
showHint4="no";
showFeedbackIndividual4="yes";
case_sensitive4="false";
partial_credit4=false;
feedbackRight4="Right! Good job!";
feedbackWrong4="Sorry, incorrect answer.";
feedbackPartial4="Partially correct.";
hint4="";
feedbackIndividual4=new Array(8);
feedbackIndividual4[0]="";
feedbackIndividual4[1]="";
feedbackIndividual4[2]="";
feedbackIndividual4[3]="";
feedbackIndividual4[4]="";
feedbackIndividual4[5]="";
feedbackIndividual4[6]="";
feedbackIndividual4[7]="";
right_answers4=new Array(3);
right_answers4[0]="2";
right_answers4[1]="0";
right_answers4[2]="1";
answer_choices4=new Array(3);
answer_choices4[0]="Watch the video to make revisions and edits so that you can then save the transcript.";
answer_choices4[1]="Play the video to become familiar with it. Make note of changes in speaker, the presence of music, and sound effects.";
answer_choices4[2]="Transcribe the video.";
tableToggle_array[4]=true;
f_done[4]=false;
feed[4]=false;
//colorChoice4="_custom";
//tableClass4="expand";
//openerImage4="none.gif";
//allowRetry4=true;
//groupID4=2;

//q_num=5;
inline_feedback5=true;
q_done[5]=false;
q_value5=1;
scoreQ[5]="yes";
mc_items5=2;
//ra_items5=1;
q_type5=2;
theQuestion5="YouTube pauses the video when you type in the Transcription Editor.";
showCorrect5="no";
showHint5="no";
showFeedbackIndividual5="yes";
case_sensitive5="false";
partial_credit5=false;
feedbackRight5="Right! Good job!";
feedbackWrong5="Sorry, incorrect answer.";
feedbackPartial5="Partially correct.";
hint5="";
feedbackIndividual5=new Array(8);
feedbackIndividual5[0]="";
feedbackIndividual5[1]="";
feedbackIndividual5[2]="";
feedbackIndividual5[3]="";
feedbackIndividual5[4]="";
feedbackIndividual5[5]="";
feedbackIndividual5[6]="";
feedbackIndividual5[7]="";
right_answers5=new Array(1);
right_answers5[0]="true";
answer_choices5=new Array(2);
answer_choices5[0]="True";
answer_choices5[1]="False";
tableToggle_array[5]=true;
f_done[5]=false;
feed[5]=false;
//colorChoice5="_custom";
//tableClass5="expand";
//openerImage5="none.gif";
//allowRetry5=true;
//groupID5=2;

